name: NDVIanalysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - geopandas
  - cartopy>=0.21
  - jupyterlab
  - ipywidgets
  - rasterio
  - pyepsg
  - folium
  - matplotlib
  - notebook
  - numpy
